options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: test
    name: golang:1.26
    entrypoint: go
    args: ["build", "./..."]

  - id: build
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE_URI", "."]

  - id: push
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE_URI"]

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - low-carbon-inventory-service
      - --image
      - $_IMAGE_URI
      - --region
      - southamerica-east1
      - --platform
      - managed
      - --add-cloudsql-instances=low-carbon-491109:southamerica-east1:low-carbon-postgres
      - --set-env-vars=DATABASE_URL=postgres://lowcarbon:LowCarbonDB2026!@/inventory?host=/cloudsql/low-carbon-491109:southamerica-east1:low-carbon-postgres&sslmode=disable,REDIS_ADDR=10.196.131.139:6379,JWT_SECRET=super-secret-jwt-key-change-in-production-2026
      - --ingress=all

images:
  - "$_IMAGE_URI"
