steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_URI', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_URI']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'low-carbon-inventory-service'
      - '--image'
      - '$_IMAGE_URI'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - '$_IMAGE_URI'

options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'