-- Migration: Drop tables for Inventory Service

DROP TABLE IF EXISTS redis_cache CASCADE;
DROP TABLE IF EXISTS user_emails CASCADE;
DROP TABLE IF EXISTS variables CASCADE;
DROP TABLE IF EXISTS emissions CASCADE;
DROP TABLE IF EXISTS inventories CASCADE;
DROP TABLE IF EXISTS links CASCADE;
DROP TABLE IF EXISTS emission_templates CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS scopes CASCADE;
DROP TABLE IF EXISTS conversion_factors CASCADE;
DROP TABLE IF EXISTS gwp_standards CASCADE;